package webapi

import java.io.FileNotFoundException

import scala.io.Source

/** Trait implementing small hack to avoid race condition when reading
  * files generated by amf Renderer.generateString.
  */
trait WaitingFileReader {

  def tryReadFile(fpath: String): String = {
    var fileContent = ""
    try {
      fileContent = Source.fromFile(fpath).getLines.mkString
    } catch {
      case ex: FileNotFoundException => {

      }
    }
    fileContent
  }

  def waitAndRead(fpath: String): String = {
    var fileContent = tryReadFile(fpath)
    var tries = 1
    val maxTries = 3
    while(fileContent == "" && tries < maxTries) {
      tries += 1
      Thread.sleep(1000)
      fileContent = tryReadFile(fpath)
    }
    fileContent
  }
}
