#%RAML 1.0 Library

types:
  Cat:
    type: object
    properties:
      name: string
  Dog:
    type: object
    properties:
      breed: string
  CatDogUnion: Cat | Dog
  CatDogMultiInheritance: [Cat, Dog]
  CatArray: Cat[]
  CatDogUnionArray: (Cat | Dog)[]
  stringArray: string[]
  stringMatrix: string[][]
  anyCat: any
  CatName: string
  CatAgeNum: number
  CatAgeInt: integer
  CatIsCool: boolean
  CatBirthDateOnly: date-only
  CatBirthTimeOnly: time-only
  CatBirthDatetimeOnly: datetime-only
  CatBirthDatetime: datetime
  CatPhoto: file
  CatosaurusNil: nil
  CatInJson:
    type: !include schemas/cat-schema.json
  CatInXml:
    type: !include schemas/cat-schema.xsd
