#%RAML 1.0 Extension
usage: Add new types
extends: ../api-with-types.raml

types:
  Person:
    type: object
    properties:
      name: string
  Admin:
    type: Person
    properties:
      cool: boolean
